@hostname = localhost
@port = 8000


### GET all values

GET /api/values HTTP/1.1
Host: {{hostname}}:{{port}}


### POST values

POST /api/values HTTP/1.1
Host: {{hostname}}:{{port}}

{
  "index": 7
}


### GET all calculated values

GET /api/values/calculated HTTP/1.1
Host: {{hostname}}:{{port}}
